# -*- coding: utf-8 -*-
"""tugas5_mtfds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIRkP-tjT6YbKtASVJ-O6y-fSuYL19ka
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

dataset = pd.read_csv("https://raw.githubusercontent.com/devanaazzahra/MTDFS/main/data.csv");

dataset.head()

dataset.describe()

dataset.corr()

dataset.sum()

ax=plt.subplots(1,1,figsize=(8,7))
seaborn.countplot('diagnosis',data=dataset)
plt.title("Breast Cancer Wisconsin Diagnosis")
plt.show()